# Exported from Render on 2026-07-28T01:09:22Z
version: "1"
projects:
- name: PTT Smokehouse Control
  environments:
  - name: Production
    services:
    - type: web
      name: ptt-smokehouse-control
      runtime: node
      repo: https://github.com/bagman3rd/ptt-smokehouse-control
      plan: starter
      envVars:
      - key: ARCHER_REQUESTS_PER_MINUTE
        sync: false
      - key: ARCHER_MAX_OUTPUT_TOKENS
        sync: false
      - key: ARCHER_OPENAI_MODEL
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: NODE_VERSION
        sync: false
      - key: NEXT_PUBLIC_APP_NAME
        sync: false
      - key: APP_SESSION_TOKEN
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ptt-smokehouse-control-db
          property: connectionString
      region: oregon
      buildCommand: corepack enable && corepack prepare pnpm@9.15.0 --activate &&
        pnpm install --prod=false --frozen-lockfile=false && pnpm run render-build
      startCommand: npm run start
      autoDeployTrigger: commit
    databases:
    - name: ptt-smokehouse-control-db
      databaseName: ptt_smokehouse_control_db
      user: ptt_smokehouse_control_db_user
      plan: basic-256mb
      region: oregon
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
      diskSizeGB: 1
