import { createHash } from 'crypto';
import { prisma } from '@/lib/prisma';
import { SquareConnector } from './square';
import { normalizePosItemName } from '@/lib/posImport';
import type { PosConnection } from '@prisma/client';

function connector(c:PosConnection){ if(c.provider==='SQUARE') return new SquareConnector(c); throw new Error(`${c.provider} connector requires provider approval and is not enabled yet.`); }
export async function syncPosConnection(connectionId:string, trigger='MANUAL', rangeStart?:Date, rangeEnd?:Date){
  const c=await prisma.posConnection.findUnique({where:{id:connectionId}}); if(!c) throw new Error('POS connection not found.');
  const started=new Date(); const start=rangeStart||new Date(Date.now()-2*86400000); const end=rangeEnd||new Date();
  const run=await prisma.posSyncRun.create({data:{restaurantId:c.restaurantId,connectionId:c.id,status:'RUNNING',trigger,startedAt:started,rangeStart:start,rangeEnd:end,cursorBefore:c.syncCursor}});
  try { const api=connector(c); const health=await api.testConnection(); if(!health.ok) throw new Error(health.message);
    const menu=await api.fetchMenu(); for(const item of menu){ await prisma.posMenuItem.upsert({where:{connectionId_externalItemId:{connectionId:c.id,externalItemId:item.id}},create:{restaurantId:c.restaurantId,connectionId:c.id,provider:c.provider,externalItemId:item.id,externalName:item.name,normalizedName:normalizePosItemName(item.name),categoryName:item.categoryName||null,active:item.active!==false},update:{externalName:item.name,normalizedName:normalizePosItemName(item.name),categoryName:item.categoryName||null,active:item.active!==false,lastSeenAt:new Date()}}); }
    let cursor:string|null|undefined=c.syncCursor, ordersRead=0,lineItemsRead=0,rawRecordsSaved=0; do { const page=await api.fetchOrders(start,end,cursor); for(const o of page.orders){ const hash=createHash('sha256').update(JSON.stringify(o.raw)).digest('hex'); await prisma.posRawRecord.upsert({where:{connectionId_recordType_externalRecordId:{connectionId:c.id,recordType:'ORDER',externalRecordId:o.id}},create:{restaurantId:c.restaurantId,connectionId:c.id,provider:c.provider,externalRecordId:o.id,recordType:'ORDER',businessDate:o.businessDate,payload:o.raw as any,payloadHash:hash,processedAt:new Date()},update:{businessDate:o.businessDate,payload:o.raw as any,payloadHash:hash,processedAt:new Date(),processingError:null}}); rawRecordsSaved++;
      const saved=await prisma.posOrder.upsert({where:{connectionId_externalOrderId:{connectionId:c.id,externalOrderId:o.id}},create:{restaurantId:c.restaurantId,connectionId:c.id,provider:c.provider,externalOrderId:o.id,externalCheckId:o.checkId,businessDate:o.businessDate,openedAt:o.openedAt,closedAt:o.closedAt,grossSalesCents:o.grossCents,discountCents:o.discountCents,netSalesCents:o.netCents,taxCents:o.taxCents,tipCents:o.tipCents,refundCents:o.refundCents,serviceChargeCents:o.serviceChargeCents,voided:o.voided,diningOption:o.diningOption,revenueCenter:o.revenueCenter,rawUpdatedAt:o.updatedAt},update:{businessDate:o.businessDate,openedAt:o.openedAt,closedAt:o.closedAt,grossSalesCents:o.grossCents,discountCents:o.discountCents,netSalesCents:o.netCents,taxCents:o.taxCents,tipCents:o.tipCents,refundCents:o.refundCents,serviceChargeCents:o.serviceChargeCents,voided:o.voided,diningOption:o.diningOption,revenueCenter:o.revenueCenter,rawUpdatedAt:o.updatedAt}});
      for(const l of o.lines){ const mapping=await prisma.menuItemMapping.findFirst({where:{restaurantId:c.restaurantId,normalizedName:normalizePosItemName(l.name),active:true}}); await prisma.posLineItem.upsert({where:{orderId_externalLineItemId:{orderId:saved.id,externalLineItemId:l.id}},create:{restaurantId:c.restaurantId,orderId:saved.id,externalLineItemId:l.id,externalItemId:l.itemId,itemName:l.name,quantity:l.quantity,grossSalesCents:l.grossCents,discountCents:l.discountCents,netSalesCents:l.netCents,taxCents:l.taxCents,refundCents:l.refundCents,voided:l.voided,modifierNames:l.modifiers,mappedProteinId:mapping?.proteinId||null,estimatedCookedLb:(mapping?.portionSizeLb||0)*l.quantity*(mapping?.yieldFactor||1)},update:{itemName:l.name,quantity:l.quantity,grossSalesCents:l.grossCents,discountCents:l.discountCents,netSalesCents:l.netCents,taxCents:l.taxCents,refundCents:l.refundCents,voided:l.voided,modifierNames:l.modifiers,mappedProteinId:mapping?.proteinId||null,estimatedCookedLb:(mapping?.portionSizeLb||0)*l.quantity*(mapping?.yieldFactor||1)}}); lineItemsRead++; } ordersRead++; }
      cursor=page.cursor;
    } while(cursor);
    await prisma.posConnection.update({where:{id:c.id},data:{status:'CONNECTED',lastSuccessfulSyncAt:new Date(),lastAttemptedSyncAt:new Date(),lastError:null,lastErrorAt:null,syncCursor:null}});
    await prisma.posSyncRun.update({where:{id:run.id},data:{status:'SUCCEEDED',completedAt:new Date(),ordersRead,lineItemsRead,rawRecordsSaved,cursorAfter:null}}); return {ok:true,ordersRead,lineItemsRead};
  } catch(e){ const message=e instanceof Error?e.message:'POS sync failed.'; await prisma.posConnection.update({where:{id:c.id},data:{status:message.includes('expired')?'REAUTH_REQUIRED':'DEGRADED',lastAttemptedSyncAt:new Date(),lastError:message,lastErrorAt:new Date()}}); await prisma.posSyncRun.update({where:{id:run.id},data:{status:'FAILED',completedAt:new Date(),errorMessage:message}}); throw e; }
}
