export type SmokerCatalogSeed = {
  brand: string;
  model: string;
  series?: string;
  smokerType: string;
  fuelType: string;
  rackCount: number;
  rackWidthIn?: number;
  rackDepthIn?: number;
  cookingAreaSqIn?: number;
  brisketCapacity: number;
  porkCapacity: number;
  ribCapacity: number;
  chickenCapacity: number;
  cookWindow?: string;
  notes?: string;
  sourceUrl?: string;
  sourceLabel?: string;
  sourceConfidence: 'OFFICIAL' | 'RESEARCHED' | 'ESTIMATED';
};

export const smokerCatalogSeeds: SmokerCatalogSeed[] = [
  { brand:'Ole Hickory Pits', model:'EL-ED/X', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:18, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:10368, brisketCapacity:40, porkCapacity:80, ribCapacity:105, chickenCapacity:144, cookWindow:'Overnight / high-volume restaurant', notes:'Official capacity lists 40 briskets, 80 Boston butts, 105 ribs, 72 whole chickens. Chicken field uses 2 breasts per whole chicken.', sourceUrl:'https://www.olehickorypits.com/products/el-edx', sourceLabel:'Ole Hickory EL-ED/X product page', sourceConfidence:'OFFICIAL' },
  { brand:'Ole Hickory Pits', model:'EL-ED', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:18, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:10368, brisketCapacity:40, porkCapacity:80, ribCapacity:105, chickenCapacity:144, cookWindow:'Overnight / high-volume restaurant', notes:'Same 18 rack 12x48, 72 sq.ft. configuration as EL-ED/X class. Capacity mirrors EL-ED/X until site-specific rack option is verified.', sourceUrl:'https://www.olehickorypits.com/products/el-ed', sourceLabel:'Ole Hickory EL-ED product page', sourceConfidence:'RESEARCHED' },
  { brand:'Ole Hickory Pits', model:'EL-EC', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:10, rackWidthIn:12, rackDepthIn:36, cookingAreaSqIn:4320, brisketCapacity:12, porkCapacity:30, ribCapacity:30, chickenCapacity:64, cookWindow:'Medium batch', notes:'Official capacity lists 12 briskets, 30 Boston butts, 30 ribs, 32 whole chickens.', sourceUrl:'https://www.olehickorypits.com/products/el-ec', sourceLabel:'Ole Hickory EL-EC product page', sourceConfidence:'OFFICIAL' },
  { brand:'Ole Hickory Pits', model:'EL-IB', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:15, rackWidthIn:12, rackDepthIn:42, cookingAreaSqIn:7560, brisketCapacity:36, porkCapacity:55, ribCapacity:75, chickenCapacity:120, cookWindow:'Overnight / restaurant', notes:'Official page states 15 12x42 racks and about 500 lb capacity; protein capacities estimated from rack area and common BBQ load density.', sourceUrl:'https://www.olehickorypits.com/products/el-ib', sourceLabel:'Ole Hickory EL-IB product page', sourceConfidence:'ESTIMATED' },
  { brand:'Ole Hickory Pits', model:'EL', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:15, rackWidthIn:12, rackDepthIn:36, cookingAreaSqIn:6480, brisketCapacity:30, porkCapacity:45, ribCapacity:60, chickenCapacity:100, cookWindow:'Overnight / restaurant', notes:'Official page states 15 12x36 racks and about 400 lb capacity; protein capacities estimated from rack area.', sourceUrl:'https://www.olehickorypits.com/products/el', sourceLabel:'Ole Hickory EL product page', sourceConfidence:'ESTIMATED' },
  { brand:'Ole Hickory Pits', model:'EL-EW', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:15, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:8640, brisketCapacity:34, porkCapacity:60, ribCapacity:85, chickenCapacity:132, cookWindow:'Overnight / restaurant', notes:'Official page states 15 12x48 racks and 60 sq.ft.; capacities estimated from rack area.', sourceUrl:'https://www.olehickorypits.com/products/el-ew', sourceLabel:'Ole Hickory EL-EW product page', sourceConfidence:'ESTIMATED' },
  { brand:'Ole Hickory Pits', model:'SSJ', series:'SSJ', smokerType:'Large rotisserie', fuelType:'Gas + wood', rackCount:0, cookingAreaSqIn:0, brisketCapacity:115, porkCapacity:150, ribCapacity:260, chickenCapacity:350, cookWindow:'Very high-volume / commissary', notes:'Official page states almost 1,500 lb capacity; protein unit capacities are estimated from app standard raw weights.', sourceUrl:'https://www.olehickorypits.com/products/ssj', sourceLabel:'Ole Hickory SSJ product page', sourceConfidence:'ESTIMATED' },
  { brand:'Ole Hickory Pits', model:'CTO', series:'CTO', smokerType:'Cabinet', fuelType:'Charcoal/wood', rackCount:4, rackWidthIn:26.5, rackDepthIn:26.5, cookingAreaSqIn:2809, brisketCapacity:8, porkCapacity:16, ribCapacity:24, chickenCapacity:48, cookWindow:'Small restaurant / catering', notes:'Official page states four 26.5x26.5 racks and 19.51 sq.ft.; capacities estimated.', sourceUrl:'https://www.olehickorypits.com/products/cto', sourceLabel:'Ole Hickory CTO product page', sourceConfidence:'ESTIMATED' },
  { brand:'Ole Hickory Pits', model:'ACE-JW', series:'ACE', smokerType:'Cabinet', fuelType:'Charcoal/wood', rackCount:0, cookingAreaSqIn:0, brisketCapacity:4, porkCapacity:12, ribCapacity:18, chickenCapacity:36, cookWindow:'Small batch / competition', notes:'Official capacity lists 4 briskets, 12 Boston butts, 18 ribs, 18 whole chickens.', sourceUrl:'https://www.olehickorypits.com/products/ace-jw', sourceLabel:'Ole Hickory ACE-JW product page', sourceConfidence:'OFFICIAL' },
  { brand:'Ole Hickory Pits', model:'Ultra Que', series:'Small cabinet', smokerType:'Cabinet', fuelType:'Charcoal/wood', rackCount:4, cookingAreaSqIn:1600, brisketCapacity:4, porkCapacity:8, ribCapacity:12, chickenCapacity:24, cookWindow:'Small batch', notes:'Catalog placeholder; verify exact current spec sheet before purchase.', sourceUrl:'https://www.olehickorypits.com/products', sourceLabel:'Ole Hickory product catalog', sourceConfidence:'ESTIMATED' },

  { brand:'Southern Pride', model:'SPK-700', series:'SPK', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:18, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:10368, brisketCapacity:40, porkCapacity:80, ribCapacity:105, chickenCapacity:144, cookWindow:'Overnight / high-volume restaurant', notes:'Spec sheet states 18 total 12x48 racks and 72 sq.ft. cooking surface; protein capacities estimated from comparable rack layout.', sourceUrl:'https://www.southernpride.com/assets/downloads/spec_sheet_spk-700.pdf', sourceLabel:'Southern Pride SPK-700 spec sheet', sourceConfidence:'RESEARCHED' },
  { brand:'Southern Pride', model:'SP-700', series:'SP', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:18, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:10368, brisketCapacity:40, porkCapacity:80, ribCapacity:105, chickenCapacity:144, cookWindow:'Overnight / high-volume restaurant', notes:'Official page states standard 18 12x48 racks with optional 12 18x48 rack system; protein capacities estimated from rack area.', sourceUrl:'https://www.southernpride.com/products/sp-700', sourceLabel:'Southern Pride SP-700 product page', sourceConfidence:'RESEARCHED' },
  { brand:'Southern Pride', model:'SPK-500', series:'SPK', smokerType:'Rotisserie mobile', fuelType:'Gas + wood', rackCount:15, rackWidthIn:12, rackDepthIn:42, cookingAreaSqIn:7560, brisketCapacity:30, porkCapacity:60, ribCapacity:60, chickenCapacity:140, cookWindow:'Medium-high restaurant / mobile', notes:'Official page states 15 12x42 racks, 60 pork butts, 60 St. Louis ribs, 70 whole chickens. Brisket estimated.', sourceUrl:'https://www.southernpride.com/products/spk-500-mobile', sourceLabel:'Southern Pride SPK-500 Mobile product page', sourceConfidence:'RESEARCHED' },
  { brand:'Southern Pride', model:'SPX-300', series:'SPX', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:9, rackWidthIn:12, rackDepthIn:42, cookingAreaSqIn:4536, brisketCapacity:18, porkCapacity:36, ribCapacity:36, chickenCapacity:84, cookWindow:'Medium batch', notes:'Listed in Southern Pride gas rotisserie family; capacities estimated from rack area and model class.', sourceUrl:'https://www.southernpride.com/assets/downloads/sept24_120v_gas_rotisserie_owners_manual_r9.pdf', sourceLabel:'Southern Pride gas rotisserie manual', sourceConfidence:'ESTIMATED' },
  { brand:'Southern Pride', model:'MLR-150', series:'MLR', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:6, rackWidthIn:12, rackDepthIn:36, cookingAreaSqIn:2592, brisketCapacity:10, porkCapacity:20, ribCapacity:24, chickenCapacity:48, cookWindow:'Small restaurant', notes:'Listed in Southern Pride gas rotisserie family; capacities estimated.', sourceUrl:'https://www.southernpride.com/assets/downloads/sept24_120v_gas_rotisserie_owners_manual_r9.pdf', sourceLabel:'Southern Pride gas rotisserie manual', sourceConfidence:'ESTIMATED' },
  { brand:'Southern Pride', model:'MLR-850', series:'MLR', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:18, rackWidthIn:18, rackDepthIn:48, cookingAreaSqIn:15552, brisketCapacity:56, porkCapacity:100, ribCapacity:150, chickenCapacity:200, cookWindow:'Very high-volume', notes:'Listed in Southern Pride gas rotisserie family; capacities estimated from larger rack configuration.', sourceUrl:'https://www.southernpride.com/assets/downloads/sept24_120v_gas_rotisserie_owners_manual_r9.pdf', sourceLabel:'Southern Pride gas rotisserie manual', sourceConfidence:'ESTIMATED' },
  { brand:'Southern Pride', model:'SPK-1400', series:'SPK', smokerType:'Large rotisserie', fuelType:'Gas + wood', rackCount:36, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:20736, brisketCapacity:80, porkCapacity:160, ribCapacity:210, chickenCapacity:288, cookWindow:'Very high-volume / commissary', notes:'Listed with SP-700 in Southern Pride rotisserie manual; capacities estimated as roughly double SPK-700.', sourceUrl:'https://www.southernpride.com/assets/downloads/sept24_120v_gas_rotisserie_owners_manual_r9.pdf', sourceLabel:'Southern Pride gas rotisserie manual', sourceConfidence:'ESTIMATED' },
  { brand:'Southern Pride', model:'SRG-800', series:'SRG', smokerType:'Gas smoker', fuelType:'Gas + wood', rackCount:18, rackWidthIn:26, rackDepthIn:56, cookingAreaSqIn:26208, brisketCapacity:70, porkCapacity:120, ribCapacity:180, chickenCapacity:260, cookWindow:'Very high-volume', notes:'Official page states standard 5 26x56 racks and maximum 18 racks; capacities estimated from maximum rack layout.', sourceUrl:'https://www.southernpride.com/products/srg-800', sourceLabel:'Southern Pride SRG-800 product page', sourceConfidence:'ESTIMATED' },
  { brand:'Southern Pride', model:'SC-200', series:'SC', smokerType:'Cabinet', fuelType:'Electric/gas + wood', rackCount:5, cookingAreaSqIn:2500, brisketCapacity:8, porkCapacity:18, ribCapacity:25, chickenCapacity:40, cookWindow:'Small batch', notes:'Catalog placeholder; verify model-specific spec sheet before purchase.', sourceUrl:'https://www.southernpride.com/products', sourceLabel:'Southern Pride product catalog', sourceConfidence:'ESTIMATED' },
  { brand:'Southern Pride', model:'SC-300', series:'SC', smokerType:'Cabinet', fuelType:'Electric/gas + wood', rackCount:8, cookingAreaSqIn:4000, brisketCapacity:14, porkCapacity:28, ribCapacity:40, chickenCapacity:64, cookWindow:'Medium batch', notes:'Catalog placeholder; verify model-specific spec sheet before purchase.', sourceUrl:'https://www.southernpride.com/products', sourceLabel:'Southern Pride product catalog', sourceConfidence:'ESTIMATED' },

  { brand:'J&R Manufacturing', model:'Little Red Smokehouse 250 FSE', series:'Little Red Smokehouse', smokerType:'Fixed rack', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:18, porkCapacity:28, ribCapacity:50, chickenCapacity:70, cookWindow:'Up to 14 hours unattended', notes:'Official page states up to 250 lb meat or 50 slabs of ribs. Brisket/pork/chicken units estimated from app weights.', sourceUrl:'https://jrmanufacturing.com/little-red-smokehouse-250-fse/', sourceLabel:'J&R Little Red Smokehouse 250 FSE product page', sourceConfidence:'RESEARCHED' },
  { brand:'J&R Manufacturing', model:'Smoke-Master 250 RFS', series:'Smoke-Master', smokerType:'Fixed rack', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:24, porkCapacity:36, ribCapacity:60, chickenCapacity:90, cookWindow:'Up to 14 hours unattended', notes:'J&R fixed-rack Smoke-Master class; capacities estimated from larger 250 RFS class vs Little Red.', sourceUrl:'https://jrmanufacturing.com/smokers/', sourceLabel:'J&R smokers catalog page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Smoke-Master 500 RFS', series:'Smoke-Master', smokerType:'Fixed rack', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:38, porkCapacity:55, ribCapacity:100, chickenCapacity:150, cookWindow:'Up to 14 hours unattended', notes:'Catalog placeholder based on Smoke-Master larger fixed-rack class; verify current J&R quote/spec sheet.', sourceUrl:'https://jrmanufacturing.com/smokers/', sourceLabel:'J&R smokers catalog page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Oyler 700', series:'Oyler', smokerType:'Rotisserie', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:76, porkCapacity:110, ribCapacity:175, chickenCapacity:240, cookWindow:'Up to 14 hours unattended', notes:'Official page states up to 1,000 lb meat; units estimated from app protein weights.', sourceUrl:'https://jrmanufacturing.com/oyler-700-smoker/', sourceLabel:'J&R Oyler 700 product page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Oyler 1300', series:'Oyler', smokerType:'Rotisserie', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:100, porkCapacity:145, ribCapacity:230, chickenCapacity:320, cookWindow:'Up to 14 hours unattended', notes:'Large Oyler class; units estimated from approximately 1,300 lb class capacity. Verify current quote/spec sheet.', sourceUrl:'https://jrmanufacturing.com/smokers/', sourceLabel:'J&R smokers catalog page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Oyler 1300E', series:'Oyler', smokerType:'Electric-assist rotisserie', fuelType:'Wood + electric assist', rackCount:0, cookingAreaSqIn:0, brisketCapacity:100, porkCapacity:145, ribCapacity:230, chickenCapacity:320, cookWindow:'Up to 14 hours unattended', notes:'Official page describes electric heat elements and convection fan; capacities mirror Oyler 1300 class until verified.', sourceUrl:'https://jrmanufacturing.com/oyler-1300e-smoker/', sourceLabel:'J&R Oyler 1300E product page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Oyler 700E', series:'Oyler', smokerType:'Electric-assist rotisserie', fuelType:'Wood + electric assist', rackCount:0, cookingAreaSqIn:0, brisketCapacity:76, porkCapacity:110, ribCapacity:175, chickenCapacity:240, cookWindow:'Up to 14 hours unattended', notes:'Estimated electric-assist variant; verify current J&R availability/spec sheet.', sourceUrl:'https://jrmanufacturing.com/smokers/', sourceLabel:'J&R smokers catalog page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Custom Smoke-Master', series:'Smoke-Master', smokerType:'Custom fixed rack', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:50, porkCapacity:75, ribCapacity:125, chickenCapacity:180, cookWindow:'Custom', notes:'Generic custom quote placeholder for J&R built-to-order models.', sourceUrl:'https://jrmanufacturing.com/smokers/', sourceLabel:'J&R smokers catalog page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Oyler 1300 Mobile', series:'Oyler', smokerType:'Mobile rotisserie', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:100, porkCapacity:145, ribCapacity:230, chickenCapacity:320, cookWindow:'Mobile / event high volume', notes:'Mobile/trailer class placeholder; verify current J&R quote/spec sheet.', sourceUrl:'https://jrmanufacturing.com/smokers/', sourceLabel:'J&R smokers catalog page', sourceConfidence:'ESTIMATED' },
  { brand:'J&R Manufacturing', model:'Little Red Smokehouse 250 FSE Electric Assist', series:'Little Red Smokehouse', smokerType:'Fixed rack electric assist', fuelType:'Wood + electric assist', rackCount:0, cookingAreaSqIn:0, brisketCapacity:18, porkCapacity:28, ribCapacity:50, chickenCapacity:70, cookWindow:'Up to 14 hours unattended', notes:'Electric-assist variation placeholder; base capacity follows Little Red 250 FSE.', sourceUrl:'https://jrmanufacturing.com/little-red-smokehouse-250-fse/', sourceLabel:'J&R Little Red Smokehouse product page', sourceConfidence:'ESTIMATED' },

  { brand:'Cookshack', model:'SM160', series:'SmartSmoker', smokerType:'Electric cabinet', fuelType:'Electric + wood', rackCount:5, rackWidthIn:18, rackDepthIn:18, cookingAreaSqIn:1620, brisketCapacity:8, porkCapacity:13, ribCapacity:15, chickenCapacity:40, cookWindow:'Small commercial batch', notes:'Official capacity is 120 lb pork butts, 100 lb brisket, 50 lb ribs, or 20 whole chickens; converted to app units.', sourceUrl:'https://www.cookshack.com/smoker-oven-model-160-stainless-steel.html', sourceLabel:'Cookshack SM160 product page', sourceConfidence:'OFFICIAL' },
  { brand:'Cookshack', model:'SM260', series:'SmartSmoker', smokerType:'Electric cabinet', fuelType:'Electric + wood', rackCount:6, rackWidthIn:23, rackDepthIn:23, cookingAreaSqIn:3174, brisketCapacity:15, porkCapacity:27, ribCapacity:30, chickenCapacity:80, cookWindow:'Medium commercial batch', notes:'Official capacity is 240 lb pork butts, 200 lb brisket, 100 lb ribs, or 40 whole chickens; converted to app units.', sourceUrl:'https://www.cookshack.com/smoker-oven-model-260-stainless-steel.html', sourceLabel:'Cookshack SM260 product page', sourceConfidence:'OFFICIAL' },
  { brand:'Cookshack', model:'SM360', series:'SmartSmoker', smokerType:'Electric cabinet', fuelType:'Electric + wood', rackCount:28, rackWidthIn:18, rackDepthIn:18, cookingAreaSqIn:9072, brisketCapacity:38, porkCapacity:61, ribCapacity:82, chickenCapacity:200, cookWindow:'High-volume commercial batch', notes:'Official capacity is 550 lb pork butts, 500 lb brisket, 270 lb ribs, or 100 whole chickens; converted to app units.', sourceUrl:'https://www.cookshack.com/smoker-oven-model-360-stainless-steel.html', sourceLabel:'Cookshack SM360 product page', sourceConfidence:'OFFICIAL' },
  { brand:'Cookshack', model:'FEC100', series:'Fast Eddy', smokerType:'Pellet fixed shelf', fuelType:'Pellet', rackCount:0, cookingAreaSqIn:0, brisketCapacity:8, porkCapacity:12, ribCapacity:20, chickenCapacity:40, cookWindow:'Small commercial pellet', notes:'Cookshack manual library lists FEC100; capacities estimated pending current product sheet.', sourceUrl:'https://www.cookshack.com/manual-instructions.html', sourceLabel:'Cookshack manuals page', sourceConfidence:'ESTIMATED' },
  { brand:'Cookshack', model:'FEC120', series:'Fast Eddy', smokerType:'Pellet fixed shelf', fuelType:'Pellet', rackCount:0, cookingAreaSqIn:0, brisketCapacity:12, porkCapacity:20, ribCapacity:30, chickenCapacity:60, cookWindow:'Medium commercial pellet', notes:'Cookshack manual library lists FEC120/FEC240 fixed shelf smoker manual; capacities estimated.', sourceUrl:'https://www.cookshack.com/manual-instructions.html', sourceLabel:'Cookshack manuals page', sourceConfidence:'ESTIMATED' },
  { brand:'Cookshack', model:'FEC240', series:'Fast Eddy', smokerType:'Pellet fixed shelf', fuelType:'Pellet', rackCount:0, cookingAreaSqIn:0, brisketCapacity:24, porkCapacity:40, ribCapacity:60, chickenCapacity:120, cookWindow:'High-volume commercial pellet', notes:'Cookshack manual library lists FEC120/FEC240 fixed shelf smoker manual; capacities estimated as roughly 2x FEC120.', sourceUrl:'https://www.cookshack.com/manual-instructions.html', sourceLabel:'Cookshack manuals page', sourceConfidence:'ESTIMATED' },
  { brand:'Cookshack', model:'FEC300-18', series:'Fast Eddy', smokerType:'Pellet rotisserie', fuelType:'Pellet', rackCount:18, cookingAreaSqIn:0, brisketCapacity:30, porkCapacity:50, ribCapacity:75, chickenCapacity:150, cookWindow:'High-volume pellet rotisserie', notes:'Cookshack manual library lists FEC300-18 rotisserie manual; capacities estimated.', sourceUrl:'https://www.cookshack.com/manual-instructions.html', sourceLabel:'Cookshack manuals page', sourceConfidence:'ESTIMATED' },
  { brand:'Cookshack', model:'FEC500', series:'Fast Eddy', smokerType:'Pellet rotisserie', fuelType:'Pellet', rackCount:0, cookingAreaSqIn:0, brisketCapacity:50, porkCapacity:85, ribCapacity:130, chickenCapacity:240, cookWindow:'Very high-volume pellet rotisserie', notes:'Cookshack manual library lists FEC500/FEC750 rotisserie manual; capacities estimated.', sourceUrl:'https://www.cookshack.com/manual-instructions.html', sourceLabel:'Cookshack manuals page', sourceConfidence:'ESTIMATED' },
  { brand:'Cookshack', model:'FEC750', series:'Fast Eddy', smokerType:'Pellet rotisserie', fuelType:'Pellet', rackCount:0, cookingAreaSqIn:0, brisketCapacity:75, porkCapacity:125, ribCapacity:190, chickenCapacity:360, cookWindow:'Very high-volume pellet rotisserie', notes:'Cookshack manual library lists FEC500/FEC750 rotisserie manual; capacities estimated.', sourceUrl:'https://www.cookshack.com/manual-instructions.html', sourceLabel:'Cookshack manuals page', sourceConfidence:'ESTIMATED' },
  { brand:'Cookshack', model:'AmeriQue SM066', series:'AmeriQue', smokerType:'Electric cabinet', fuelType:'Electric + wood', rackCount:4, rackWidthIn:14, rackDepthIn:18, cookingAreaSqIn:1008, brisketCapacity:4, porkCapacity:6, ribCapacity:8, chickenCapacity:18, cookWindow:'Small batch / residential-commercial crossover', notes:'Official page states 50 lb total capacity and four 14x18 racks; app capacities estimated.', sourceUrl:'https://www.cookshack.com/amerique-electric-smoker-oven.html', sourceLabel:'Cookshack AmeriQue product page', sourceConfidence:'ESTIMATED' },
  { brand:'Southern Pride', model:'SRG-400', series:'SRG', smokerType:'Gas smoker', fuelType:'Gas + wood', rackCount:10, rackWidthIn:26, rackDepthIn:56, cookingAreaSqIn:14560, brisketCapacity:38, porkCapacity:70, ribCapacity:100, chickenCapacity:150, cookWindow:'High-volume', notes:'SRG family placeholder based on SRG rack architecture; verify model-specific current spec sheet.', sourceUrl:'https://www.southernpride.com/products', sourceLabel:'Southern Pride product catalog', sourceConfidence:'ESTIMATED' },
  { brand:'Cookshack', model:'FEC120 Mobile', series:'Fast Eddy', smokerType:'Pellet fixed shelf mobile', fuelType:'Pellet', rackCount:0, cookingAreaSqIn:0, brisketCapacity:12, porkCapacity:20, ribCapacity:30, chickenCapacity:60, cookWindow:'Mobile commercial pellet', notes:'Mobile/configuration placeholder using FEC120 planning capacities; verify current product availability and spec sheet.', sourceUrl:'https://www.cookshack.com/manual-instructions.html', sourceLabel:'Cookshack manuals page', sourceConfidence:'ESTIMATED' },

  { brand:'M&M BBQ Company', model:'MM1000', series:'Commercial Grade', smokerType:'Rotisserie', fuelType:'Wood-fired', rackCount:18, rackWidthIn:47, rackDepthIn:17, cookingAreaSqIn:14382, brisketCapacity:55, porkCapacity:95, ribCapacity:145, chickenCapacity:240, cookWindow:'High-volume restaurant', notes:'Official page states 18 rack capacity with 47x17 racks and 12 included racks; protein capacities estimated from rack area.', sourceUrl:'https://mmbbqcompany.com/product/mm1000/', sourceLabel:'M&M BBQ Company MM1000 product page', sourceConfidence:'ESTIMATED' },
  { brand:'M&M BBQ Company', model:'OS500', series:'Offset Series', smokerType:'Offset', fuelType:'Wood-fired', rackCount:3, cookingAreaSqIn:0, brisketCapacity:25, porkCapacity:35, ribCapacity:50, chickenCapacity:90, cookWindow:'Offset / restaurant or catering', notes:'Official page states 3 stainless steel racks; protein capacities estimated from offset class.', sourceUrl:'https://mmbbqcompany.com/product/os500/', sourceLabel:'M&M BBQ Company OS500 product page', sourceConfidence:'ESTIMATED' },
  { brand:'M&M BBQ Company', model:'OS1000', series:'Offset Series', smokerType:'Offset', fuelType:'Wood-fired', rackCount:4, cookingAreaSqIn:0, brisketCapacity:40, porkCapacity:60, ribCapacity:80, chickenCapacity:140, cookWindow:'Large offset / restaurant or catering', notes:'Official page states 4 stainless steel racks; protein capacities estimated from offset class.', sourceUrl:'https://mmbbqcompany.com/product/os1000/', sourceLabel:'M&M BBQ Company OS1000 product page', sourceConfidence:'ESTIMATED' },
  { brand:'M&M BBQ Company', model:'Texas Smoke King 250G', series:'Texas Smoke King', smokerType:'Offset', fuelType:'Wood-fired', rackCount:2, cookingAreaSqIn:0, brisketCapacity:8, porkCapacity:12, ribCapacity:18, chickenCapacity:40, cookWindow:'Small commercial / catering', notes:'Product family placeholder; verify specific chamber and rack dimensions before purchase.', sourceUrl:'https://mmbbqcompany.com/our-products/', sourceLabel:'M&M BBQ Company products page', sourceConfidence:'ESTIMATED' },
  { brand:'M&M BBQ Company', model:'Texas Smoke King 500G', series:'Texas Smoke King', smokerType:'Offset', fuelType:'Wood-fired', rackCount:3, cookingAreaSqIn:0, brisketCapacity:16, porkCapacity:24, ribCapacity:36, chickenCapacity:75, cookWindow:'Commercial catering', notes:'Product family placeholder; verify specific chamber and rack dimensions before purchase.', sourceUrl:'https://mmbbqcompany.com/our-products/', sourceLabel:'M&M BBQ Company products page', sourceConfidence:'ESTIMATED' },
  { brand:'M&M BBQ Company', model:'Goldee\'s Backyard Offset', series:'Goldee\'s', smokerType:'Offset', fuelType:'Wood-fired', rackCount:2, cookingAreaSqIn:0, brisketCapacity:6, porkCapacity:8, ribCapacity:12, chickenCapacity:24, cookWindow:'Small batch / backyard-commercial crossover', notes:'Listed by M&M product page; capacities estimated and not intended for high-volume restaurant production.', sourceUrl:'https://mmbbqcompany.com/our-products/', sourceLabel:'M&M BBQ Company products page', sourceConfidence:'ESTIMATED' },
  { brand:'M&M BBQ Company', model:'El Rey Woodfire Grill', series:'Live Fire', smokerType:'Woodfire grill', fuelType:'Wood-fired', rackCount:0, cookingAreaSqIn:0, brisketCapacity:0, porkCapacity:0, ribCapacity:0, chickenCapacity:0, cookWindow:'Grill, not primary smokehouse', notes:'Included for equipment catalog completeness; not counted as smoker capacity by default.', sourceUrl:'https://mmbbqcompany.com/our-products/', sourceLabel:'M&M BBQ Company products page', sourceConfidence:'RESEARCHED' },
  { brand:'M&M BBQ Company', model:'The War Chest Direct Heat Cooker', series:'Live Fire', smokerType:'Direct heat cooker', fuelType:'Wood/charcoal', rackCount:0, cookingAreaSqIn:0, brisketCapacity:0, porkCapacity:0, ribCapacity:0, chickenCapacity:0, cookWindow:'Direct heat / specialty', notes:'Included for catalog completeness; not counted as low-and-slow smoker capacity by default.', sourceUrl:'https://mmbbqcompany.com/our-products/', sourceLabel:'M&M BBQ Company products page', sourceConfidence:'RESEARCHED' }
];

export async function ensureSmokerCatalog(prisma: any) {
  for (const item of smokerCatalogSeeds) {
    await prisma.smokerCatalog.upsert({
      where: { brand_model: { brand: item.brand, model: item.model } },
      update: {
        series: item.series || null,
        smokerType: item.smokerType,
        fuelType: item.fuelType,
        rackCount: item.rackCount,
        rackWidthIn: item.rackWidthIn ?? null,
        rackDepthIn: item.rackDepthIn ?? null,
        cookingAreaSqIn: item.cookingAreaSqIn ?? null,
        brisketCapacity: item.brisketCapacity,
        porkCapacity: item.porkCapacity,
        ribCapacity: item.ribCapacity,
        chickenCapacity: item.chickenCapacity,
        cookWindow: item.cookWindow || null,
        notes: item.notes || null,
        sourceUrl: item.sourceUrl || null,
        sourceLabel: item.sourceLabel || null,
        sourceConfidence: item.sourceConfidence,
        active: true
      },
      create: {
        brand: item.brand,
        model: item.model,
        series: item.series || null,
        smokerType: item.smokerType,
        fuelType: item.fuelType,
        rackCount: item.rackCount,
        rackWidthIn: item.rackWidthIn ?? null,
        rackDepthIn: item.rackDepthIn ?? null,
        cookingAreaSqIn: item.cookingAreaSqIn ?? null,
        brisketCapacity: item.brisketCapacity,
        porkCapacity: item.porkCapacity,
        ribCapacity: item.ribCapacity,
        chickenCapacity: item.chickenCapacity,
        cookWindow: item.cookWindow || null,
        notes: item.notes || null,
        sourceUrl: item.sourceUrl || null,
        sourceLabel: item.sourceLabel || null,
        sourceConfidence: item.sourceConfidence,
        active: true
      }
    });
  }
}
