export type SmokerCatalogSeed = {
  brand: string;
  model: string;
  series?: string;
  smokerType: string;
  fuelType: string;
  rackCount?: number | null;
  rackWidthIn?: number | null;
  rackDepthIn?: number | null;
  cookingAreaSqIn?: number | null;
  brisketCapacity?: number | null;
  porkCapacity?: number | null;
  ribCapacity?: number | null;
  chickenCapacity?: number | null;
  cookWindow?: string;
  notes?: string;
  sourceUrl?: string;
  sourceLabel?: string;
  sourceConfidence: 'OFFICIAL' | 'OFFICIAL_PARTIAL';
};

function wholeChickenToBreasts(count: number | null | undefined) {
  return typeof count === 'number' ? count * 2 : null;
}

function row(item: SmokerCatalogSeed): SmokerCatalogSeed {
  return item;
}

export const smokerCatalogSeeds: SmokerCatalogSeed[] = [
  // Ole Hickory Pits — official manufacturer capacity pages. Chicken is stored as breast-equivalent units where the official page gives whole chickens.
  row({ brand:'Ole Hickory Pits', model:'EL-ED/X', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:12, rackWidthIn:18, rackDepthIn:48, cookingAreaSqIn:10368, brisketCapacity:40, porkCapacity:80, ribCapacity:105, chickenCapacity:wholeChickenToBreasts(72), cookWindow:'High-volume rotisserie', notes:'Official manufacturer capacity: 40 briskets, 80 Boston butts, 105 ribs, 72 whole chickens. Stored chicken capacity is 144 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/el-edx', sourceLabel:'Ole Hickory EL-ED/X product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'EL-ED', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:18, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:10368, brisketCapacity:40, porkCapacity:80, ribCapacity:105, chickenCapacity:wholeChickenToBreasts(72), cookWindow:'High-volume rotisserie', notes:'Official manufacturer capacity: 40 briskets, 80 Boston butts, 105 ribs, 72 whole chickens. Stored chicken capacity is 144 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/el-ed', sourceLabel:'Ole Hickory EL-ED product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'EL-EC', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:12, porkCapacity:30, ribCapacity:30, chickenCapacity:wholeChickenToBreasts(32), cookWindow:'Medium rotisserie', notes:'Official manufacturer capacity: 12 briskets, 30 Boston butts, 30 ribs, 32 whole chickens. Stored chicken capacity is 64 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/el-ec', sourceLabel:'Ole Hickory EL-EC product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'EL', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:20, porkCapacity:40, ribCapacity:60, chickenCapacity:wholeChickenToBreasts(50), cookWindow:'Restaurant rotisserie', notes:'Official manufacturer capacity: 20 briskets, 40 Boston butts, 60 ribs, 50 whole chickens. Stored chicken capacity is 100 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/el', sourceLabel:'Ole Hickory EL product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'EL-IB', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:20, porkCapacity:40, ribCapacity:60, chickenCapacity:wholeChickenToBreasts(60), cookWindow:'Restaurant rotisserie', notes:'Official manufacturer capacity: 20 briskets, 40 Boston butts, 60 ribs, 60 whole chickens. Stored chicken capacity is 120 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/el-ib', sourceLabel:'Ole Hickory EL-IB product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'EL-EW', series:'EL', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:20, porkCapacity:50, ribCapacity:60, chickenCapacity:wholeChickenToBreasts(70), cookWindow:'Restaurant rotisserie', notes:'Official manufacturer capacity: 20 briskets, 50 Boston butts, 60 ribs, 70 whole chickens. Stored chicken capacity is 140 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/el-ew', sourceLabel:'Ole Hickory EL-EW product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'SSL', series:'SS', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:20, porkCapacity:50, ribCapacity:60, chickenCapacity:wholeChickenToBreasts(70), cookWindow:'Restaurant rotisserie', notes:'Official manufacturer capacity: 20 briskets, 50 Boston butts, 60 ribs, 70 whole chickens. Stored chicken capacity is 140 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/ssl', sourceLabel:'Ole Hickory SSL product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'SSE', series:'SS', smokerType:'Rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:30, porkCapacity:60, ribCapacity:90, chickenCapacity:wholeChickenToBreasts(90), cookWindow:'High-volume rotisserie', notes:'Official manufacturer capacity: 30 briskets, 60 Boston butts, 90 ribs, 90 whole chickens. Stored chicken capacity is 180 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/sse', sourceLabel:'Ole Hickory SSE product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'SSJ-AE', series:'SSJ', smokerType:'Large rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:60, porkCapacity:120, ribCapacity:150, chickenCapacity:wholeChickenToBreasts(105), cookWindow:'Very high-volume rotisserie', notes:'Official manufacturer capacity: 60 briskets, 120 Boston butts, 150 ribs, 105 whole chickens. Stored chicken capacity is 210 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/ssj-ae', sourceLabel:'Ole Hickory SSJ-AE product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'SSJ', series:'SSJ', smokerType:'Large rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:74, porkCapacity:150, ribCapacity:175, chickenCapacity:wholeChickenToBreasts(120), cookWindow:'Very high-volume rotisserie', notes:'Official manufacturer capacity: 74 briskets, 150 Boston butts, 175 ribs, 120 whole chickens. Stored chicken capacity is 240 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/ssj', sourceLabel:'Ole Hickory SSJ product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'CTO', series:'CTO', smokerType:'Cabinet', fuelType:'Gas + wood', rackCount:null, brisketCapacity:12, porkCapacity:24, ribCapacity:24, chickenCapacity:wholeChickenToBreasts(48), cookWindow:'Cabinet / small restaurant', notes:'Official manufacturer capacity: 12 briskets, 24 Boston butts, 24 ribs, 48 whole chickens. Stored chicken capacity is 96 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/cto', sourceLabel:'Ole Hickory CTO product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'CTO-DW', series:'CTO', smokerType:'Cabinet', fuelType:'Gas + wood', rackCount:null, cookingAreaSqIn:5760, brisketCapacity:30, porkCapacity:60, ribCapacity:48, chickenCapacity:wholeChickenToBreasts(96), cookWindow:'Large cabinet', notes:'Official manufacturer capacity: 30 briskets, 60 Boston butts, 48 ribs, 96 whole chickens. Stored chicken capacity is 192 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/cto-dw', sourceLabel:'Ole Hickory CTO-DW product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'CTO-TQ', series:'CTO', smokerType:'Cabinet', fuelType:'Gas + wood', rackCount:null, brisketCapacity:9, porkCapacity:18, ribCapacity:18, chickenCapacity:wholeChickenToBreasts(36), cookWindow:'Three-quarter cabinet', notes:'Official manufacturer capacity: 9 briskets, 18 Boston butts, 18 ribs, 36 whole chickens. Stored chicken capacity is 72 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/cto-tq', sourceLabel:'Ole Hickory CTO-TQ product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'ACE-BP', series:'ACE', smokerType:'Cabinet', fuelType:'Gas + wood', rackCount:null, brisketCapacity:9, porkCapacity:18, ribCapacity:18, chickenCapacity:wholeChickenToBreasts(36), cookWindow:'Small cabinet', notes:'Official manufacturer capacity: 9 briskets, 18 Boston butts, 18 ribs, 36 whole chickens. Stored chicken capacity is 72 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/ace-bp', sourceLabel:'Ole Hickory ACE-BP product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'ACE-JW', series:'ACE', smokerType:'Cabinet', fuelType:'Gas + wood', rackCount:null, brisketCapacity:4, porkCapacity:12, ribCapacity:18, chickenCapacity:wholeChickenToBreasts(18), cookWindow:'Small cabinet', notes:'Official manufacturer capacity: 4 briskets, 12 Boston butts, 18 ribs, 18 whole chickens. Stored chicken capacity is 36 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/ace-jw', sourceLabel:'Ole Hickory ACE-JW product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Ole Hickory Pits', model:'Ultra Que', series:'Small cabinet', smokerType:'Cabinet', fuelType:'Gas + wood', rackCount:null, brisketCapacity:4, porkCapacity:12, ribCapacity:18, chickenCapacity:wholeChickenToBreasts(18), cookWindow:'Small cabinet', notes:'Official manufacturer capacity: 4 briskets, 12 Boston butts, 18 ribs, 18 whole chickens. Stored chicken capacity is 36 breast-equivalent units.', sourceUrl:'https://www.olehickorypits.com/products/ultra-que', sourceLabel:'Ole Hickory Ultra Que product page', sourceConfidence:'OFFICIAL' }),

  // Southern Pride — official manufacturer product pages / product-comparison table. No estimated rows.

  row({ brand:'Southern Pride', model:'MLR-150 Mobile', series:'MLR Mobile', smokerType:'Mobile gas rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:null, porkCapacity:24, ribCapacity:null, chickenCapacity:null, cookWindow:'Mobile gas rotisserie', notes:'Official manufacturer page snippet confirms 24 pork butts. Other protein capacities were not captured in verified source snippets for this build, so they are intentionally blank.', sourceUrl:'https://www.southernpride.com/products/mlr-150-mobile', sourceLabel:'Southern Pride MLR-150 Mobile product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'Southern Pride', model:'SPX-300 Mobile', series:'SPX Mobile', smokerType:'Mobile gas rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:null, porkCapacity:32, ribCapacity:null, chickenCapacity:null, cookWindow:'Mobile gas rotisserie', notes:'Official product-family listing identifies SPX-300 Mobile adjacent to the SPX-300 model; only verified published capacities from source snippets are loaded. Unverified capacities are intentionally blank.', sourceUrl:'https://www.southernpride.com/products/spx-300', sourceLabel:'Southern Pride SPX-300 product page / mobile listing', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'Southern Pride', model:'SPK-500 Mobile', series:'SPK Mobile', smokerType:'Mobile gas rotisserie', fuelType:'Gas + wood', rackCount:15, rackWidthIn:12, rackDepthIn:42, brisketCapacity:null, porkCapacity:60, ribCapacity:null, chickenCapacity:null, cookWindow:'Mobile gas rotisserie', notes:'Official manufacturer page snippet confirms 15 racks and 60 pork butts. Other protein capacities were not captured in verified source snippets for this build, so they are intentionally blank.', sourceUrl:'https://www.southernpride.com/products/spk-500-mobile', sourceLabel:'Southern Pride SPK-500 Mobile product page', sourceConfidence:'OFFICIAL_PARTIAL' }),

  row({ brand:'Southern Pride', model:'SC-100', series:'SC', smokerType:'Electric smoker', fuelType:'Electric + wood', rackCount:null, brisketCapacity:4, porkCapacity:12, ribCapacity:12, chickenCapacity:wholeChickenToBreasts(24), cookWindow:'Small electric smoker', notes:'Official manufacturer capacity: 12 pork butts, 12 baby back ribs, 24 whole chickens, 4 beef briskets. Stored chicken capacity is 48 breast-equivalent units.', sourceUrl:'https://www.southernpride.com/products/sc-100', sourceLabel:'Southern Pride SC-100 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Southern Pride', model:'SC-300', series:'SC', smokerType:'Electric smoker', fuelType:'Electric + wood', rackCount:null, brisketCapacity:10, porkCapacity:30, ribCapacity:25, chickenCapacity:null, cookWindow:'Electric smoker', notes:'Official manufacturer capacity found for pork butts, St. Louis ribs, and beef brisket. Whole chicken count was not captured in verified source snippets for this build, so chicken is intentionally blank.', sourceUrl:'https://www.southernpride.com/products/sc-300', sourceLabel:'Southern Pride SC-300 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'Southern Pride', model:'MLR-150', series:'MLR', smokerType:'Gas rotisserie', fuelType:'Gas + wood', rackCount:12, rackWidthIn:10, rackDepthIn:22, brisketCapacity:8, porkCapacity:24, ribCapacity:24, chickenCapacity:wholeChickenToBreasts(32), cookWindow:'Small gas rotisserie', notes:'Official manufacturer capacity: 12 racks, 24 pork butts, 24 St. Louis ribs, 32 whole chickens, 8 beef briskets. Stored chicken capacity is 64 breast-equivalent units.', sourceUrl:'https://www.southernpride.com/products/mlr-150', sourceLabel:'Southern Pride MLR-150 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Southern Pride', model:'SPX-300', series:'SPX', smokerType:'Gas rotisserie', fuelType:'Gas + wood', rackCount:12, rackWidthIn:12, rackDepthIn:30, brisketCapacity:8, porkCapacity:32, ribCapacity:24, chickenCapacity:wholeChickenToBreasts(40), cookWindow:'Gas rotisserie', notes:'Official manufacturer capacity: 32 pork butts, 24 St. Louis ribs, 40 whole chickens, 8 beef briskets. Stored chicken capacity is 80 breast-equivalent units.', sourceUrl:'https://www.southernpride.com/products/spx-300', sourceLabel:'Southern Pride SPX-300 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Southern Pride', model:'SRG-400', series:'SRG', smokerType:'Gas smoker', fuelType:'Gas + wood', rackCount:null, brisketCapacity:18, porkCapacity:42, ribCapacity:70, chickenCapacity:null, cookWindow:'Gas smoker', notes:'Official manufacturer capacity found for 42 pork butts, 70 St. Louis ribs, and 18 beef briskets. Whole chicken count was not captured in verified source snippets for this build, so chicken is intentionally blank.', sourceUrl:'https://www.southernpride.com/products/srg-400', sourceLabel:'Southern Pride SRG-400 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'Southern Pride', model:'SPK-500', series:'SPK', smokerType:'Gas rotisserie', fuelType:'Gas + wood', rackCount:15, rackWidthIn:12, rackDepthIn:42, cookingAreaSqIn:7560, brisketCapacity:20, porkCapacity:60, ribCapacity:60, chickenCapacity:null, cookWindow:'Medium-high gas rotisserie', notes:'Official manufacturer capacity found for 60 pork butts, 60 St. Louis ribs, and 20 beef briskets. Whole chicken count was not captured in verified source snippets for this build, so chicken is intentionally blank.', sourceUrl:'https://www.southernpride.com/products/spk-500', sourceLabel:'Southern Pride SPK-500 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'Southern Pride', model:'SP-700', series:'SP', smokerType:'Gas rotisserie', fuelType:'Gas + wood', rackCount:18, rackWidthIn:12, rackDepthIn:48, cookingAreaSqIn:10368, brisketCapacity:24, porkCapacity:84, ribCapacity:72, chickenCapacity:null, cookWindow:'High-volume gas rotisserie', notes:'Official manufacturer capacity found for 84 pork butts, 72 St. Louis ribs, and 24 beef briskets. Whole chicken count was not captured in verified source snippets for this build, so chicken is intentionally blank.', sourceUrl:'https://www.southernpride.com/products/sp-700', sourceLabel:'Southern Pride SP-700 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'Southern Pride', model:'SRG-800', series:'SRG', smokerType:'Gas smoker', fuelType:'Gas + wood', rackCount:null, brisketCapacity:24, porkCapacity:72, ribCapacity:60, chickenCapacity:wholeChickenToBreasts(96), cookWindow:'High-volume gas smoker', notes:'Official manufacturer capacity: 72 pork butts, 60 baby back ribs, 96 whole chickens, 24 beef briskets. Stored chicken capacity is 192 breast-equivalent units.', sourceUrl:'https://www.southernpride.com/products/srg-800', sourceLabel:'Southern Pride SRG-800 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Southern Pride', model:'SPK-1400', series:'SPK', smokerType:'Gas rotisserie', fuelType:'Gas + wood', rackCount:null, brisketCapacity:36, porkCapacity:108, ribCapacity:120, chickenCapacity:null, cookWindow:'Very high-volume gas rotisserie', notes:'Official manufacturer capacity found for 108 pork butts, 120 St. Louis ribs, and 36 beef briskets. Whole chicken count was not captured in verified source snippets for this build, so chicken is intentionally blank.', sourceUrl:'https://www.southernpride.com/products/spk-1400', sourceLabel:'Southern Pride SPK-1400 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),

  // J&R Manufacturing — official manufacturer capacity pages. Chicken is manufacturer half-chicken count; app stores it in the chicken capacity field as official chicken units, not an estimate.
  row({ brand:'J&R Manufacturing', model:'Little Red Smokehouse 250 FSE', series:'Little Red Smokehouse', smokerType:'Fixed rack smoker', fuelType:'Wood', rackCount:10, rackWidthIn:28, rackDepthIn:20.5, brisketCapacity:15, porkCapacity:null, ribCapacity:50, chickenCapacity:150, cookWindow:'Fixed rack, up to 250 lb', notes:'Official manufacturer capacity: 250 lb total, 10-15 briskets, 50 spare-rib slabs, 150 chicken halves. Pork-butt count is not published, so pork capacity is intentionally blank.', sourceUrl:'https://jrmanufacturing.com/little-red-smokehouse-250-fse/', sourceLabel:'J&R Little Red Smokehouse 250 FSE product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'J&R Manufacturing', model:'Smoke-Master 250 RFS', series:'Smoke-Master', smokerType:'Fixed rack smoker', fuelType:'Wood', rackCount:7, rackWidthIn:39, rackDepthIn:32, brisketCapacity:35, porkCapacity:null, ribCapacity:70, chickenCapacity:210, cookWindow:'Fixed rack, up to 600 lb', notes:'Official manufacturer capacity: 600 lb total, 30-35 briskets, 70 spare-rib slabs, 210 chicken halves. Pork-butt count is not published, so pork capacity is intentionally blank.', sourceUrl:'https://jrmanufacturing.com/smoke-master-250-rfs/', sourceLabel:'J&R Smoke-Master 250 RFS product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'J&R Manufacturing', model:'Oyler 700', series:'Oyler', smokerType:'Rotisserie smoker', fuelType:'Wood', rackCount:18, rackWidthIn:17, rackDepthIn:42, brisketCapacity:60, porkCapacity:null, ribCapacity:144, chickenCapacity:324, cookWindow:'Rotisserie, up to 1,000 lb', notes:'Official manufacturer capacity: 1,000 lb total, 48-60 briskets, 144 spare-rib slabs, 324 chicken halves. Pork-butt count is not published, so pork capacity is intentionally blank.', sourceUrl:'https://jrmanufacturing.com/oyler-700-smoker/', sourceLabel:'J&R Oyler 700 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'J&R Manufacturing', model:'Oyler 700E', series:'Oyler', smokerType:'Rotisserie smoker', fuelType:'Wood + electric assist', rackCount:18, rackWidthIn:17, rackDepthIn:42, brisketCapacity:60, porkCapacity:null, ribCapacity:144, chickenCapacity:324, cookWindow:'Rotisserie, up to 1,000 lb', notes:'Official manufacturer capacity: 1,000 lb total, 48-60 briskets, 144 spare-rib slabs, 324 chicken halves. Pork-butt count is not published, so pork capacity is intentionally blank.', sourceUrl:'https://jrmanufacturing.com/oyler-700e-smoker/', sourceLabel:'J&R Oyler 700E product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'J&R Manufacturing', model:'Oyler 1300', series:'Oyler', smokerType:'Rotisserie smoker', fuelType:'Wood', rackCount:18, rackWidthIn:54, rackDepthIn:18, brisketCapacity:72, porkCapacity:null, ribCapacity:288, chickenCapacity:432, cookWindow:'Rotisserie, up to 2,000 lb', notes:'Official manufacturer capacity: 2,000 lb total, 60-72 briskets, 288 spare-rib slabs, 432 chicken halves. Pork-butt count is not published, so pork capacity is intentionally blank.', sourceUrl:'https://jrmanufacturing.com/oyler-1300-smoker/', sourceLabel:'J&R Oyler 1300 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'J&R Manufacturing', model:'Oyler 1300E', series:'Oyler', smokerType:'Rotisserie smoker', fuelType:'Wood + electric assist', rackCount:18, rackWidthIn:18, rackDepthIn:54, brisketCapacity:72, porkCapacity:null, ribCapacity:288, chickenCapacity:432, cookWindow:'Rotisserie, up to 2,000 lb', notes:'Official manufacturer capacity: 2,000 lb total, 60-72 briskets, 288 spare-rib slabs, 432 chicken halves. Pork-butt count is not published, so pork capacity is intentionally blank.', sourceUrl:'https://jrmanufacturing.com/oyler-1300e-smoker/', sourceLabel:'J&R Oyler 1300E product page', sourceConfidence:'OFFICIAL_PARTIAL' }),

  // Cookshack — official manufacturer product pages. Cookshack publishes capacities in pounds for pork, brisket, and ribs; those official pounds are stored as-is in catalog notes and as pound values in the capacity fields.
  row({ brand:'Cookshack', model:'SM160', series:'SmartSmoker', smokerType:'Electric cabinet', fuelType:'Electric + wood', rackCount:5, rackWidthIn:18, rackDepthIn:18, cookingAreaSqIn:1620, brisketCapacity:100, porkCapacity:120, ribCapacity:50, chickenCapacity:wholeChickenToBreasts(20), cookWindow:'Commercial electric smoker', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 120 lb pork butts, 100 lb brisket, 50 lb ribs, or 20 whole chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/smoker-oven-model-160-stainless-steel.html', sourceLabel:'Cookshack SM160 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'SM260', series:'SmartSmoker', smokerType:'Electric cabinet', fuelType:'Electric + wood', rackCount:6, rackWidthIn:23, rackDepthIn:23, cookingAreaSqIn:3456, brisketCapacity:200, porkCapacity:240, ribCapacity:100, chickenCapacity:wholeChickenToBreasts(40), cookWindow:'Commercial electric smoker', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 240 lb pork butts, 200 lb brisket, 100 lb ribs, or 40 whole chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/smoker-oven-model-260-stainless-steel.html', sourceLabel:'Cookshack SM260 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'SM360', series:'SmartSmoker', smokerType:'Electric cabinet', fuelType:'Electric + wood', rackCount:28, rackWidthIn:18, rackDepthIn:18, cookingAreaSqIn:9072, brisketCapacity:500, porkCapacity:550, ribCapacity:270, chickenCapacity:wholeChickenToBreasts(100), cookWindow:'Commercial electric smoker', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 550 lb pork butts, 500 lb brisket, 270 lb ribs, or 100 whole chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/smoker-oven-model-360-stainless-steel.html', sourceLabel:'Cookshack SM360 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'FEC100', series:'Fast Eddy', smokerType:'Pellet fixed shelf', fuelType:'Pellet', rackCount:4, rackWidthIn:23, rackDepthIn:17, cookingAreaSqIn:1564, brisketCapacity:80, porkCapacity:100, ribCapacity:60, chickenCapacity:wholeChickenToBreasts(24), cookWindow:'Commercial pellet smoker', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 100 lb pork butts, 80 lb brisket, 60 lb ribs, or 24 chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/fast-eddy-model-fec100.html', sourceLabel:'Cookshack FEC100 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'FEC120', series:'Fast Eddy', smokerType:'Pellet fixed shelf', fuelType:'Pellet', rackCount:5, rackWidthIn:23, rackDepthIn:17, cookingAreaSqIn:1955, brisketCapacity:120, porkCapacity:150, ribCapacity:90, chickenCapacity:wholeChickenToBreasts(30), cookWindow:'Commercial pellet smoker', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 150 lb pork butts, 120 lb brisket, 90 lb ribs, or 30 chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/fast-eddys-by-cookshack-model-fec120.html', sourceLabel:'Cookshack FEC120 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'FEC240', series:'Fast Eddy', smokerType:'Pellet fixed shelf', fuelType:'Pellet', rackCount:8, rackWidthIn:23, rackDepthIn:17, cookingAreaSqIn:3128, brisketCapacity:240, porkCapacity:250, ribCapacity:180, chickenCapacity:wholeChickenToBreasts(60), cookWindow:'Commercial pellet smoker', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 250 lb pork butt, 240 lb brisket, 180 lb ribs, or 60 whole chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/fast-eddys-model-fec240.html', sourceLabel:'Cookshack FEC240 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'FEC300-18', series:'Fast Eddy', smokerType:'Pellet rotisserie', fuelType:'Pellet', rackCount:12, rackWidthIn:18, rackDepthIn:25, cookingAreaSqIn:5400, brisketCapacity:300, porkCapacity:350, ribCapacity:100, chickenCapacity:wholeChickenToBreasts(45), cookWindow:'Commercial pellet rotisserie', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 350 lb pork butts, 300 lb brisket, 100 lb ribs, or 45 chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/fast-eddys-by-cookshack-model-300-18.html', sourceLabel:'Cookshack FEC300-18 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'FEC500', series:'Fast Eddy', smokerType:'Pellet rotisserie', fuelType:'Pellet', rackCount:15, rackWidthIn:11.5, rackDepthIn:42, cookingAreaSqIn:7350, brisketCapacity:450, porkCapacity:500, ribCapacity:150, chickenCapacity:wholeChickenToBreasts(70), cookWindow:'Commercial pellet rotisserie', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 500 lb pork butts, 450 lb brisket, 150 lb ribs, or 70 whole chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/fast-eddy-model-fec500-stainless-steel.html', sourceLabel:'Cookshack FEC500 product page', sourceConfidence:'OFFICIAL' }),
  row({ brand:'Cookshack', model:'FEC750', series:'Fast Eddy', smokerType:'Pellet rotisserie', fuelType:'Pellet', rackCount:15, rackWidthIn:11.5, rackDepthIn:60, cookingAreaSqIn:10800, brisketCapacity:700, porkCapacity:750, ribCapacity:300, chickenCapacity:wholeChickenToBreasts(110), cookWindow:'Commercial pellet rotisserie', notes:'Official manufacturer capacity is pounds for pork/brisket/ribs: 750 lb pork butts, 700 lb brisket, 300 lb ribs, or 110 whole chickens. Capacity fields for pork/brisket/ribs are official pounds, not unit counts.', sourceUrl:'https://www.cookshack.com/fast-eddy-model-750-stainless-steel.html', sourceLabel:'Cookshack FEC750 product page', sourceConfidence:'OFFICIAL' }),

  // M&M BBQ Company — official manufacturer specs only. No protein counts are invented. Rows without official protein capacities remain blank.
  row({ brand:'M&M BBQ Company', model:'MM1000', series:'Commercial Grade', smokerType:'Rotisserie', fuelType:'Wood-fired', rackCount:18, rackWidthIn:47, rackDepthIn:17, brisketCapacity:null, porkCapacity:null, ribCapacity:null, chickenCapacity:null, cookWindow:'Commercial rotisserie', notes:'Official manufacturer page publishes 18 racks, 47 x 17 in., with 12 racks included. No official protein-count capacities were found in the verified source for this build, so meat capacities are intentionally blank.', sourceUrl:'https://mmbbqcompany.com/product/mm1000/', sourceLabel:'M&M MM1000 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'M&M BBQ Company', model:'OS500', series:'Offset Series', smokerType:'Offset', fuelType:'Wood-fired', rackCount:3, brisketCapacity:null, porkCapacity:null, ribCapacity:null, chickenCapacity:null, cookWindow:'Offset smoker', notes:'Official manufacturer page publishes 3 stainless steel racks. No official protein-count capacities were found in the verified source for this build, so meat capacities are intentionally blank.', sourceUrl:'https://mmbbqcompany.com/product/os500/', sourceLabel:'M&M OS500 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'M&M BBQ Company', model:'OS1000', series:'Offset Series', smokerType:'Offset', fuelType:'Wood-fired', rackCount:4, brisketCapacity:null, porkCapacity:null, ribCapacity:null, chickenCapacity:null, cookWindow:'Large offset smoker', notes:'Official manufacturer page publishes 4 stainless steel racks. No official protein-count capacities were found in the verified source for this build, so meat capacities are intentionally blank.', sourceUrl:'https://mmbbqcompany.com/product/os1000/', sourceLabel:'M&M OS1000 product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'M&M BBQ Company', model:'Texas Smoke King Series', series:'Texas Smoke King', smokerType:'Offset', fuelType:'Wood-fired', rackCount:null, brisketCapacity:7, porkCapacity:null, ribCapacity:null, chickenCapacity:null, cookWindow:'100-gallon offset', notes:'Official manufacturer page states the Texas Smoke King cooks up to 7 full briskets. Pork, rib, and chicken capacities were not published in the verified source, so those fields are intentionally blank.', sourceUrl:'https://mmbbqcompany.com/product/texas-smoke-king/', sourceLabel:'M&M Texas Smoke King product page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'M&M BBQ Company', model:"Goldee's Backyard Offset", series:"Goldee's", smokerType:'Offset', fuelType:'Wood-fired', rackCount:null, brisketCapacity:6, porkCapacity:null, ribCapacity:9, chickenCapacity:15, cookWindow:'Backyard/commercial crossover offset', notes:'Official manufacturer capacity: 6 briskets, 9 ribs, 15 chickens, 15 turkey breasts, 40 sausages. Pork capacity is not published, so pork is intentionally blank.', sourceUrl:'https://mmbbqcompany.com/product/goldees-backyard-offset/', sourceLabel:"M&M Goldee's Backyard Offset product page", sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'M&M BBQ Company', model:'El Rey Woodfire Grill', series:'Live Fire', smokerType:'Woodfire grill', fuelType:'Wood-fired', rackCount:null, brisketCapacity:null, porkCapacity:null, ribCapacity:null, chickenCapacity:null, cookWindow:'Live-fire grill, not smoker capacity', notes:'Manufacturer product-family row only. No official smoker protein capacities were found in the verified source for this build; meat capacities are intentionally blank.', sourceUrl:'https://mmbbqcompany.com/our-products/', sourceLabel:'M&M product family page', sourceConfidence:'OFFICIAL_PARTIAL' }),
  row({ brand:'M&M BBQ Company', model:'The War Chest Direct Heat Cooker', series:'Live Fire', smokerType:'Direct heat cooker', fuelType:'Wood/charcoal', rackCount:null, brisketCapacity:null, porkCapacity:null, ribCapacity:null, chickenCapacity:null, cookWindow:'Direct heat cooker, not primary smokehouse capacity', notes:'Manufacturer product-family row only. No official smoker protein capacities were found in the verified source for this build; meat capacities are intentionally blank.', sourceUrl:'https://mmbbqcompany.com/our-products/', sourceLabel:'M&M product family page', sourceConfidence:'OFFICIAL_PARTIAL' })
];

export async function ensureSmokerCatalog(prisma: any) {
  const verifiedKeys = smokerCatalogSeeds.map((item) => `${item.brand}|||${item.model}`);
  const existing = await prisma.smokerCatalog.findMany({ select: { id: true, brand: true, model: true } });
  const obsoleteIds = existing.filter((item: any) => !verifiedKeys.includes(`${item.brand}|||${item.model}`)).map((item: any) => item.id);
  if (obsoleteIds.length) {
    await prisma.smokerCatalog.updateMany({ where: { id: { in: obsoleteIds } }, data: { active: false, sourceConfidence: 'RETIRED_UNVERIFIED', notes: 'Retired by Build 5.7.0 because prior catalog row used estimated/unverified smoker capacities.' } });
  }

  for (const item of smokerCatalogSeeds) {
    await prisma.smokerCatalog.upsert({
      where: { brand_model: { brand: item.brand, model: item.model } },
      update: {
        series: item.series || null,
        smokerType: item.smokerType,
        fuelType: item.fuelType,
        rackCount: item.rackCount ?? null,
        rackWidthIn: item.rackWidthIn ?? null,
        rackDepthIn: item.rackDepthIn ?? null,
        cookingAreaSqIn: item.cookingAreaSqIn ?? null,
        brisketCapacity: item.brisketCapacity ?? null,
        porkCapacity: item.porkCapacity ?? null,
        ribCapacity: item.ribCapacity ?? null,
        chickenCapacity: item.chickenCapacity ?? null,
        cookWindow: item.cookWindow || null,
        notes: item.notes || null,
        sourceUrl: item.sourceUrl || null,
        sourceLabel: item.sourceLabel || null,
        sourceConfidence: item.sourceConfidence,
        active: true
      },
      create: {
        brand: item.brand,
        model: item.model,
        series: item.series || null,
        smokerType: item.smokerType,
        fuelType: item.fuelType,
        rackCount: item.rackCount ?? null,
        rackWidthIn: item.rackWidthIn ?? null,
        rackDepthIn: item.rackDepthIn ?? null,
        cookingAreaSqIn: item.cookingAreaSqIn ?? null,
        brisketCapacity: item.brisketCapacity ?? null,
        porkCapacity: item.porkCapacity ?? null,
        ribCapacity: item.ribCapacity ?? null,
        chickenCapacity: item.chickenCapacity ?? null,
        cookWindow: item.cookWindow || null,
        notes: item.notes || null,
        sourceUrl: item.sourceUrl || null,
        sourceLabel: item.sourceLabel || null,
        sourceConfidence: item.sourceConfidence,
        active: true
      }
    });
  }
}
