ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorRecoveryCodes" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorKeyVersion" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "twoFactorRecoveryDisplay" TEXT;
